name: 'Test'
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
          dotnet-quality: 'ga'

      - name: Run Tests
        run: dotnet test